version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: products
  redis:
    image: redis
    ports:
      - 6379:6379